%% Example - Plot Ic(B) data for a single array
% Tjerk Reintsema
% 01-10-2021
%
% Plots and optionally saves Ic(B) curves from data file generated by
% simulation script.
close all
clearvars

file = ".\data\10a8h.mat";

load(file);

%% Plotting

SAVE_FIGURES = false;
filestring = "10a8h";
titlestring = "I_c of a 10 by 10 array, with an 8 by 8 hole";
% xlims = 'auto';
ylims = [0, 0.25];
figno1 = 10;
figno2 = 20;

% All curves
[fig1, ax1] = plot_IcB(Ic_f_list, f_list, nHole_list, 'figno', figno1, 'titlestring', titlestring, 'ylims', ylims);

% Maximum Ic(B)
[fig2, ax2] = plot_IcB_max(Ic_f_max, f_list, 'figno', figno2, 'titlestring', titlestring, 'ylims', ylims);

% Saving figures
if SAVE_FIGURES
    if not(isfolder(".\figures\"))
        mkdir(".\figures\")
    end
    exportgraphics(ax1, strcat(".\figures\", filestring, "_all.png"), "Resolution", 400)
    exportgraphics(ax2, strcat(".\figures\", filestring, "_max.png"), "Resolution", 400)
end
